apiVersion: v1
kind: Service
metadata:
  name: uwu-links
  labels:
    app: uwu-links
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 3333
      targetPort: 3333
  # Replace with the IP of your minikube node / master node
  externalIPs:
    - 192.168.64.2
    - 172.17.0.4
  selector:
    app: uwu-links
    tier: backend
